language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
env:
  - MYSQL_POOL=20 MYSQL_HOST=127.0.0.1 MYSQL_USER=travis MYSQL_PASSWD='' MYSQL_DB=test MYSQL_CHARSET=utf8
install: "pip install -e ."
before_script:
  - mysql -e "create database IF NOT EXISTS test;" -utravis
  - pip install -r requirements.dev.txt
script: ./run-tests